CouchDBAllEventsPath: "https://event-svc-pvt.sxsw.com/xomo12eco/_design/api/_view/events?include_docs=true"
CouchDBUserName: "downtown"
CouchDBPassword: "j662B0685t"
CouchUserPath: "https://event-svc-pvt.sxsw.com/xomo12eco/_design/api/_view/users?include_docs=true"
BaseEventURL: "http://schedule.sxsweco.com/events/"
TwitterSearchURL: "http://search.twitter.com/search.json"
TwitterHashTag: "#sxsw"
FacebookBaseURL: "http://graph.facebook.com"
HTTPNumberOfAttempts: "5"
ReportPageSize: "50"
ErrorLogAgeInDays: "60"